### ISSUE TITLE
nil pointer evaluating interface {}.repository

### ISSUE THREAD

**Issue by blair-anson** [bambash/helm-cronjobs#15]
Hi,
Creating a brand new cron job works fine, but when `helm upgrade --install` is called to update an existing cron job I see the following error....
```
helm.go:76: [debug] template: app/charts/datacollector/templates/cronjob.yaml:44:27: executing "app/charts/datacollector/templates/cronjob.yaml" at <$job.image.repository>: nil pointer evaluating interface {}.repository
```
my values.yaml looks like this...
```
  jobs:
  - name: pdschedule
    image:
      repository: private/pdschedule
      tag: 2
      imagePullPolicy: IfNotPresent
    schedule: 0 */4 * * *
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    command:
    - /bin/sh
    args:
    - -c
    - java $JAVA_OPTS -jar /app.jar com.example.app
```
